export default [
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'Test',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '632763723',
    familyName: 'berger',
    givenName: 'flavie',
    phoneNumbers: [{ label: 'mobile', number: '‪+44 1111 111111' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: '',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '64B331A59D586460',
    familyName: 'Flower',
    givenName: 'Rose',
    phoneNumbers: [{ label: 'mobile', number: '0222 222222' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'F&C',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '18001C7E7760F66:ABPerson',
    familyName: 'Walc',
    givenName: 'Robert',
    phoneNumbers: [{ label: 'mobile', number: '0333 333333' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'Cottons',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '0184A8203679EAA',
    familyName: 'Krak',
    givenName: 'Anna',
    phoneNumbers: [{ label: 'mobile', number: '0444 444444' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: '',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '0274FC133',
    familyName: 'Malek',
    givenName: 'Martin',
    phoneNumbers: [{ label: 'mobile', number: '07960 111111' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'F&C',
    thumbnailPath: '',
    jobTitle: '',
    recordID: 'B1D8D-B5D6-7D6E3E983656',
    familyName: 'Slack',
    givenName: 'Sara',
    phoneNumbers: [{ label: 'mobile', number: '07476 999999' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'ABC',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '95CF6B1E-A11E-4163-AA8F-70A5B9D4F127',
    familyName: 'Marlone',
    givenName: 'Don',
    phoneNumbers: [{ label: 'mobile', number: '+44 7777 777777' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'F&C',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '3255F90A520',
    familyName: 'Mal',
    givenName: 'Brandon',
    phoneNumbers: [{ label: 'mobile', number: '+44 7931 898989' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'ABC',
    thumbnailPath: '',
    jobTitle: '',
    recordID: 'C6C19C05-C05B380545AE',
    familyName: 'Slon',
    givenName: 'Slawek',
    phoneNumbers: [{ label: 'mobile', number: '07746 123467' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: '',
    thumbnailPath: '',
    jobTitle: '',
    recordID: 'A5C1C:ABPerson',
    familyName: 'Surname',
    givenName: 'Test',
    phoneNumbers: [{ label: 'home', number: '07922 000000' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: '',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '2025DFBE20CA528F9844',
    familyName: 'Something',
    givenName: 'Tinene',
    phoneNumbers: [{ label: 'home', number: '07789 111111' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: 'ABC',
    thumbnailPath: '',
    jobTitle: '',
    recordID: '45C4966F4C01852B4',
    familyName: '',
    givenName: 'Tom',
    phoneNumbers: [{ label: 'home', number: '07581 111111' }],
    hasThumbnail: false },
  { emailAddresses: [],
    postalAddresses: [],
    middleName: '',
    company: '',
    thumbnailPath: '',
    jobTitle: '',
    recordID: 'A4A23712D0790FF8:ABPerson',
    familyName: 'Polish',
    givenName: 'Daniel',
    phoneNumbers: [{ label: 'mobile', number: '+48 608 000 000' }],
    hasThumbnail: false }
];
